### ISSUE TITLE
Encoding a '+' in an existing URL

### ISSUE THREAD

**Issue by VikramHauteLook** [webignition/url#5]
If you have an existing URL that looks like: `http://example.com/index.php?param1=test+value`. This library will replace the `+` with `%2B` when you do `$responseUrl = (string) $responseUrl;`.

Example:

```
$url = "http://example.com/index.php?param1=test+value";
echo (string)$url;
```

Outputs:

```
http://example.com/index.php?param1=test%2Bvalue
```

Expectation:

```
http://example.com/index.php?param1=test+value
```

**Comment by marcelklehr** [comment]
This is causing a problem for me!

**Comment by marcelklehr** [comment]
(The plus sign encodes a space, so reencoding it changes spaces to pluses.)

**Comment by webignition** [comment]
Hi @marcelklehr!

URLs cast to strings are encoded as per [RFC 3986](https://tools.ietf.org/html/rfc3986). As per RFC 3986, the plus character does not hold any special meaning. Encoding `+` to `%2B` is correct.

The plus character is to be treated as a space only for `application/x-www-form-urlencoded` content. From the perspective of this library, URLs are just strings without any context. We can't assume that the plus character has any special meaning.

For cases where the plus character denotes an encoded space, the percent-encoded form of `%20` is also valid. 

The most safe option is to always encode spaces as `%20`.

**Comment by marcelklehr** [comment]
To cite from the aforementioned RFC:

> 2.2.  Reserved Characters
>
>   URIs include components and subcomponents that are delimited by
   characters in the "reserved" set.  These characters are called
   "reserved" because they may (or may not) be defined as delimiters by
   the generic syntax, by each scheme-specific syntax, or by the
   implementation-specific syntax of a URI's dereferencing algorithm.
   If data for a URI component would conflict with a reserved
   character's purpose as a delimiter, then the conflicting data must be
   percent-encoded before the URI is formed.
>
>      reserved    = gen-delims / sub-delims
>
>      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
>
>      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
>                  / "*" / "+" / "," / ";" / "="
>
>   The purpose of reserved characters is to provide a set of delimiting
   characters that are distinguishable from other data within a URI.
   URIs that differ in the replacement of a reserved character with its
   corresponding percent-encoded octet are not equivalent.  Percent-
   encoding a reserved character, or decoding a percent-encoded octet
   that corresponds to a reserved character, will change how the URI is
   interpreted by most applications.  Thus, characters in the reserved
   set are protected from normalization and are therefore safe to be
   used by scheme-specific and producer-specific algorithms for
   delimiting data subcomponents within a URI.


As you will notice the list of reserved characters includes the plus sign. I interpret this as: 'Don't arbitrarily change a + to a %2B', what do you think?

**Comment by webignition** [comment]
I see what you're saying and so I did a bit of investigation (it's been a while since I actively worked on this library).

A `Url` object does not cause the changes you state. A `NormalisedUrl` object does perform such changes. URL normalisation is inherently opinionated since there's no unified consensus on what the normal form of a URL should be.

Example:

```php
$source = 'http://example.com/path+name/?param1=test+value';

$urlObject = new Url($url);
$normalisedUrlObject = new NormalisedUrl($url);

var_dump($url, (string) $url, (string) $normalisedUrlObject);

// string(47) "http://example.com/path+name/?param1=test+value"
// string(47) "http://example.com/path+name/?param1=test+value"
// string(49) "http://example.com/path+name/?param1=test%2Bvalue"
```

Would the use of a `Url` instead of a `NormalisedUrl` be suitable for what you're doing?

**Comment by marcelklehr** [comment]
> Would the use of a Url instead of a NormalisedUrl be suitable for what you're doing?

I don't think so, because I want to compare URLs, so I'd like to normalize the URLs in a way that preserves semantics. Additionally, normalization should be idempotent (i.e. if I normalize twice, it shouldn't make a difference) -- I'm not sure if this is currently the case or not, though.

**Comment by webignition** [comment]
Fair enough.

To be honest, I've not considered whether the normalisation process is idempotent and I agree that this certainly should be the case.

I'll be sure to examine this as part of the charges for version 3.

In the meantime, if you need to compare URLs for equivalence, would the comparison of two `NormalisedUrl` instances suffice?

Whilst the string representation of each instance may not be what you expect, might it be the case that this is suitable for determining if two URLs are the same?

**Comment by marcelklehr** [comment]
> I'll be sure to examine this as part of the charges for version 3.

Awesome! :)

> In the meantime, if you need to compare URLs for equivalence, would the comparison of two NormalisedUrl instances suffice?

This doesn't work for me, sadly, because I compare them on the client in javascript, so the js implementation and the PHP implementation need to be compatible :/

**Comment by webignition** [comment]
Could you point me in the direction of the JS URL normalised that you're using?

This would help me figure out if there any compatibility concerns with respect to your last comment.

**Comment by marcelklehr** [comment]
Here's the code: https://github.com/sindresorhus/normalize-url/blob/master/index.js
This issue came up as a result of using both libraries in unison (here's the failing test case: https://travis-ci.org/marcelklehr/floccus/jobs/459902870#L2455 ).

**Comment by webignition** [comment]
Cool, thanks for the links.

In the failing build, and for the highlighted line showing the failure, what is the URL before normalization? 

I can see what the URL is being normalized to and how it is not the same in both cases but I can't see what the URL is before normalization.

**Comment by webignition** [comment]
@marcelklehr  Furthermore, of the options offered by the JS normalizer, which are you using?

**Comment by webignition** [comment]
Should be all sorted in [3.0](https://github.com/webignition/url/releases/tag/3.0).

Still, can't be sure without knowing what the un-normalized URL was ...

**Comment by marcelklehr** [comment]
Oh, sorry. `http://foo.com/?bar=foo+bar` would be normalized to `http://foo.com/?bar=foo%2Bbar`, just like in the OP. I don't use any of the options of the js normalizer.

**Comment by webignition** [comment]
Cool, you should all be fine then with the 3.0 release.

**Comment by marcelklehr** [comment]
Thanks! :)
